### ISSUE TITLE
DegC vs Kelvin and Humidity Ratio

### ISSUE THREAD

**Issue by mathewgreen** [oehoe/signalk-raspberry-pi-bme680#1]
Output from this sensor appears to be in degrees C, the SignalK spec seems to be in Kelvin.  Can I put the offset of 273.15 somewhere?

**Comment by mathewgreen** [comment]
So have found         await this.setTempOffset(0);  in bme680.js which if I change to         await this.setTempOffset(273.15);
seems to work.  Not sure if this will affect the calibration.

**Comment by mathewgreen** [comment]
Also found changing bme680Data.data.humidity = await this.calcHumidity(adc_hum) / 1000.0 to 100000.0 gives me the correct ratio in Wilhelmsk.

**Comment by mathewgreen** [comment]
Calibration is affected by changing offset.  Have changed 
bme680Data.data.temperature = temperature / 100.0;
to
bme680Data.data.temperature = temperature / 100.0 + 273.15;

This appears to work fine, and humidity is not affected.

**Comment by oehoe** [comment]
Thanks for your suggestions, I'll update the plugin before the season starts :)

**Comment by oehoe** [comment]
Should now be fixed by @romton843
