### ISSUE TITLE
Little improvements suggestions

### ISSUE THREAD

**Issue by romton843** [oehoe/signalk-raspberry-pi-bme680#2]
Hi, first, I wanted to thank you for your work.
I just have few suggestions to make it better:
- It would be great to be able to choose differents paths for the temperature, humidity and pressure.
Because my sensor is inside but to be able to use the pressure for weather tendency (with signalk-barometer-trend node that complements the sensor very well), I have to set the pressure as "environment.outside.pressure", but would love to be able to keep "inside" for temperature and humidity.
- The temperature is indeed in Celcius but shows up as Kelvin in Signal K...
- It would be awesome to get the gas and IAQ available in Signal K. I managed to get that to influxdb thru a script called bme680_to_influxdb by ayeks on github but I wish that could be part of your plugin.
Anyway, thanks again and happy new year.
Romain

**Comment by oehoe** [comment]
I'll update the plugin to Kelvin. I've looked into the AQI but it seemed a delicate number. I'll look into it.

**Comment by romton843** [comment]
The IAQ requires processing and therfore might not be so easy to make available but the gas imput in Ohm would be better than nothing. Also the unit for the pressure is in Pa but the number is in hPa...
Thanks again for your answer and your work. If there is anything I can do to help, let me know.
Best regards.
Romain

**Comment by romton843** [comment]
Hi, I sent a pull request for the temperature to be in Kelvin and the pressure in pa so that Signal K is not thinking it's 10hpa and -290 degrees celcius.
So far I'm using the path mapper plugin to deal with my paths issue and it works fine.
However, I can implement a second Signal K path to have two different ones, one for the pressure and another one for the temperature and humidity or three different paths if you prefer.
Let me know if you prefer not changing that part since path mapper is always a solution.
I can also try to implement the gas data and a IAQ using the working code from [https://github.com/ayeks/bme680_to_influxdb](https://github.com/ayeks/bme680_to_influxdb).
Best regards.
Romain

**Comment by oehoe** [comment]
You're welcome to propose the change as you see fit. Only issue is I can't check the changes as my sensor is in my boat which is in storage :) You can add a function in which you rewrite the air quality function from the proposed repository. I will accept your changes and test it next month.

**Comment by romton843** [comment]
Hi, I managed to get the air quality index to Signal K but so far I have to run a separate python program that starts the sensor when I start or restart the plugin. I'm definitely not a professionnal programmer and I'm figuring that out very slowly.
I'll keep you updated.

**Comment by romton843** [comment]
Hi,
I finally got the time to do it and it's working perfectly for me.
Feel free to try it before merging and to rewrite my code as you please of course (one more time, I'm not a professionnal).
Also, I did a 0 to 500 index (0 being good and 500 being bad) for the Air Quality since it seems to be pretty common.
Some people might prefer a 0 to 100 scale with ) being bad and 100 being good.
That's an easy modification.
Best regards.
Romain
