### ISSUE TITLE
Humidity value should be divided by 100

### ISSUE THREAD

**Issue by szabolcszijarto** [oehoe/signalk-raspberry-pi-bme680#6]
Hello
Thank you first of all for this plugin, really useful! :)
I noticed that humidity is sent to signalk as for example value = 46.254 and unit = ratio
I think that's wrong because the true value is actually 46.254 _percent_
To be in unit "ratio", the value should be 0.46254
The problem becomes apparent on the KIP instrument panel, showing values with unit "ratio" always as percentage, multiplying it by 100. For me it shows right now 4625%, which is 100 times what it should be.

**Comment by romton843** [comment]
I modified it on my branch and pulled a request.

**Comment by oehoe** [comment]
Fixed by romton843. Thanks
