### ISSUE TITLE
NPM release out of date

### ISSUE THREAD

**Issue by tvr256** [oehoe/signalk-raspberry-pi-bme680#7]
Thanks for a great plugin!

A number of changes were made by @romton843 last year to support air quality, and these have been merged into the latest Git repository. But when loading the plugin into SignalK, it doesn't include these changes. I think the changes need to be released to NPM, is this something you can do?

**Comment by oehoe** [comment]
I updated the npm package. I did notice that the dependency for this package has been updated. I don't have a running signalK installation to test this plugin with the updated dependency. Maybe @romton843 can test with the new version of the bme680 package?

**Comment by tvr256** [comment]
Tested and working perfectly. Thanks for the quick fix!

![image](https://github.com/oehoe/signalk-raspberry-pi-bme680/assets/117984987/a196710c-ad69-45ce-984a-fb046d5f6cbc)
